replicaCount: 1

clusterName: "my-cluster"

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8181

ingress:
  enabled: true
  className: nginx
  annotations: {}

certificate:
  enabled: true
  issuer:
    name: selfsigned
    kind: ClusterIssuer
  
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi