apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-config
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      
      sendfile        on;
      keepalive_timeout  65;
      
      server {
        listen 80;
        server_name localhost;
        
        location / {
          return 200 'Cluster: {{ .Values.clusterName | default "Unknown" }}
Pod: $hostname
Time: {{ now | date "2006-01-02 15:04:05" }}';
          add_header Content-Type text/plain;
        }
      }
    } 