apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-app.fullname" . }}
  labels:
    app: nginx
spec:
  type: {{include "nginx-deployment.fullname" .}}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx